### ISSUE TITLE
When filtered Log entries the shown Entrys should be counted for the Max visible

### ISSUE THREAD

**Issue by Serverfrog** [seiyria/Roguathia#75] opened 2016-01-06 16:57 UTC
Currently are 50 Log entries total "existing", regardless if they are not visible or not.
Example: if Combat is filtered out, so that somebody can't see them, only 15 Entries are Visible because of the max Size of 50.
It would be nice if the maximal visible entries are 50 (or configurable in the Settings) and not the "existing" entries.
Best Solution: 
- a option to set if either the max visible or max existing Entries should be counted
- a option how many Entries with the default of 50

**Comment by seiyria** [comment] 2016-01-06 17:03
I was planning to do this, but it makes things more computationally expensive and it also makes things more tricky. It's more computationally expensive because you have to filter entries out instead of just hiding them, so you can ensure you always have an upper limit of X entries.

It's more tricky because I [cap the array size at 100](https://github.com/seiyria/Roguathia/blob/master/src/js/angular/controllers/Log.js#L29) (so the log doesn't get too large). Consider here the case where you have, say, 40 Meta entries, 30 Battle entries, 20 Item entries and 10 Dungeon entries. You want to filter them out so you only ever see Meta entries, but all those other items are still taking space in the array, meaning that there is only a finite amount of space available.

To do as you suggest, they'd each have to have their own capped collection at 100, and then they'd have to be merged together, finding the first 100 of the proper filtered type(s) and nothing else, which is significantly more overhead. 

I don't see any significant benefit in doing it this way, which is why I didn't.

**Comment by Serverfrog** [comment] 2016-01-06 17:08
The other possible way to do this would be not to add them in the Log if they are filtered out(if that is possible, Doesn't understand Angular pretty well).
In that case the computing time would be also reduced if they are filtered out and i found the cap size after i created the issue. 

The benefit would be that when someone idling for a longer time and he only want to see how many rounds he won/loose and/or found items, he couldn't do that because they are filtered out because of the combat log.

**Comment by seiyria** [comment] 2016-01-06 17:11
You could do that, but the problem is: what if you want to see historical messages from another message type? You can't, because you removed the ability to do so.

As for being able to see wins/losses, #51 covers that pretty well. So far, that's the only use-case that's been brought up where it makes sense to have a separate, dedicated log. Unless there are more use-cases that I'm missing, I'm going to close this one for now because I don't see any real value coming out of this unfortunately.

**Closed as completed by seiyria** 2016-01-06 17:11 UTC
