### ISSUE TITLE
Monk keeps equipping weapons

### ISSUE THREAD

**Issue by OneWingedDevil** [seiyria/Roguathia#64] opened 2015-12-06 04:31 UTC
Every time a monk picks up a weapon, they default to equipping it if they don't have one already. Given their aptitude for unarmed combat, they should default to going without one.

Only workaround I have so far is to have monks play a race without arms, like a snake.

**Comment by seiyria** [comment] 2015-12-06 04:40
this is essentially a duplicate of #52.

**Closed as completed by seiyria** 2015-12-06 04:40 UTC
